services:
  - type: web
    name: cybershield-backend
    env: python
    rootDir: backend
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: SECRET_KEY
        sync: false
    plan: free

